name: CI for Angular
on: push
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 20.x
        uses: actions/setup-node@v2
        with:
          node-version: 20.x
      - name: Install dependencies
        run: npm ci
      - name: Run unit tests
        run: ng test --no-watch --code-coverage --browsers=ChromeHeadlessCI